version: '3.8'

services:
  naturanet:
    build:
      context: .
    image: natura-net
    container_name: natura-net
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000" # PHP FPM exposed here for nginx
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: php-fpm

  nginx:
    image: nginx:latest
    container_name: nginx-natura-net
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - naturanet

volumes:
  dbdata:
