version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: your_db
      DB_USERNAME: your_user
      DB_PASSWORD: your_pass
    command: php artisan serve --host=0.0.0.0 --port=9000

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: your_db
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
