# version: '3.8'

# services:
#   naturanet:
#     build:
#       context: .
#     image: natura-net
#     container_name: natura-net
#     restart: always
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#     ports:
#       - "8080:8080"
#     env_file:
#       - .env
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_PORT: ${DB_PORT}
#       DB_DATABASE: ${DB_DATABASE}
#       DB_USERNAME: ${DB_USERNAME}
#       DB_PASSWORD: ${DB_PASSWORD}
#     command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8080

version: '3.8'

services:
  naturanet:
    build:
      context: .
    image: natura-net
    container_name: natura-net
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}