name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        if: ${{ github.ref_name == 'main' }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/project/naturanet
            git pull origin main

            cp .env.example .env

            echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            echo ".env created with DB & APP_KEY from secrets..."

            docker-compose down
            docker-compose build --build-arg ENV_FILE=.env --no-cache
            docker-compose up -d

            # Check if Docker container is running on port 9000
            sudo lsof -i :9000 || echo "No service is using port 9000"
