name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Deploying Laravel to VPS..."

            # Pastikan folder ada
            sudo mkdir -p /var/www/naturanet
            cd /var/www/naturanet

            # Pull latest changes
            if [ ! -d .git ]; then
              git clone git@github.com:username/naturanet.git .
            else
              git reset --hard
              git pull origin main
            fi

            # Set environment file
            cat <<EOF > .env
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_URL=https://yourdomain.com

            LOG_CHANNEL=stack

            SUPERADMIN_ROLE=${{ secrets.SUPERADMIN_ROLE }}
            SUPERADMIN_USERNAME=${{ secrets.SUPERADMIN_USERNAME }}
            SUPERADMIN_NAME=${{ secrets.SUPERADMIN_NAME }}
            SUPERADMIN_PASSWORD=${{ secrets.SUPERADMIN_PASSWORD }}

            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120

            MEMCACHED_HOST=127.0.0.1

            REDIS_HOST=127.0.0.1
            REDIS_PASSWORD=null
            REDIS_PORT=6379

            MAIL_MAILER=smtp
            MAIL_HOST=mailpit
            MAIL_PORT=1025
            MAIL_USERNAME=null
            MAIL_PASSWORD=null
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS="hello@example.com"
            MAIL_FROM_NAME="\${APP_NAME}"

            EOF

            # Set permission untuk Laravel
            # sudo chown -R www-data:www-data /var/www/naturanet
            # sudo chmod -R 775 storage bootstrap/cache

            # Install dependencies
            composer install --no-dev --optimize-autoloader

            # Migrate database
            php artisan migrate --force

            # Clear & cache configs
            php artisan config:clear
            php artisan route:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache

            # Reload PHP-FPM
            sudo systemctl reload php8.2-fpm

            echo "✅ Deployment selesai!"
