name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        if: ${{ github.ref_name == 'main' }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/project/naturanet
            git pull origin main

            cp .env.example .env

            # echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            # echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            # echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            # echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            # echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            # echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            cat <<EOF > .env
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_URL=https://yourdomain.com

            LOG_CHANNEL=stack

            SUPERADMIN_ROLE=${{ secrets.SUPERADMIN_ROLE }}
            SUPERADMIN_USERNAME=${{ secrets.SUPERADMIN_USERNAME }}
            SUPERADMIN_NAME=${{ secrets.SUPERADMIN_NAME }}
            SUPERADMIN_PASSWORD=${{ secrets.SUPERADMIN_PASSWORD }}

            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120

            MEMCACHED_HOST=127.0.0.1

            REDIS_HOST=127.0.0.1
            REDIS_PASSWORD=null
            REDIS_PORT=6379

            MAIL_MAILER=smtp
            MAIL_HOST=mailpit
            MAIL_PORT=1025
            MAIL_USERNAME=null
            MAIL_PASSWORD=null
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS="hello@example.com"
            MAIL_FROM_NAME="\${APP_NAME}"

            EOF

            echo ".env created with DB & APP_KEY from secrets..."

            docker-compose down --remove-orphans
            docker-compose build --build-arg ENV_FILE=.env --no-cache
            docker-compose up -d

            # Check if Docker container is running on port 9000
            sudo lsof -i :9000 || echo "No service is using port 9000"
